account/urls.py
from django.urls import path
from . import views

app_name = 'accountApp'

urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('registration_success/', views.success, name='success'),
    path('login/', views.logintUser, name='loginUser'),
    path('logout/', views.logoutUser, name='logoutUser'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='homeApp')),
    path('account/', include('account.urls', namespace='accountApp')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'homeApp'

urlpatterns = [
    path('', views.home_page, name = 'home_page')    
]

account/models.py
from django.db import models

# Create your models 
# class MyForm(models.Model):
#     name = models.CharField(max_length=100)
#     email = models.CharField(max_length=100)
#     password = models.CharField(max_length=32)

home/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    

account/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

# Create your views here.

# uname = User.objects.filter('username')
def registration(request):
    title = 'Registration'
    form = RegistrationForm(request.POST)


    context = {
        'form' : form,
        'title' : title,
        }
    
    if request.user.is_authenticated:
        return redirect('homeApp:home_page')
    
    else:
        # print('hello reg')
        # form = RegistrationForm()
        
        if request.method == "POST":
            username = request.POST.get('username')
            email = request.POST.get('email')
            pass1 = request.POST.get('password1')
            pass2 = request.POST.get('password2')

            print(username, email, pass1, pass2)
            # user=authenticate(request, username = username)

            def clean_name(self):
                userVal = self.cleaned_data['username']
                print('38', userVal)

            if User.objects.filter(username=username).exists():
                context = {
                    'usererror':'Username or email already exist',
                    }
                return render(request, 'account/registration_form.html', context)
            elif User.objects.filter(email=email).exists():
                context = {
                    'usererror':'email already exist',
                    }
                return render(request, 'account/registration_form.html', context)

            elif pass2 != pass1:
                context = {
                    'passerror':'pass not matched',
                    }
                return render(request, 'account/registration_form.html', context)
            
            else:
                new_user = User.objects.create_user(username, email, pass1)
                new_user.save()
                return redirect('homeApp:home_page')

                

            # form = RegistrationForm(request.POST)
            # print(form)
            # print(form.errors)
            # if form.is_valid():
            #     form.save()
            #     return redirect('accountApp:success')

    return render(request, 'account/registration_form.html', context)

def success(request):
    return render(request, 'account/success.html')


def logoutUser(request):
    logout(request)
    return redirect('homeApp:home_page')

def logintUser(request):
    if request.user.is_authenticated:
        return redirect('homeApp:home_page')
    else:
        print('hello login')
        form = RegistrationForm()
        if request.method == "POST":
            form = RegistrationForm(request.POST)
            print(form)
            if form.is_valid():
                form.save()

    return render(request, 'account/login.html', {'form': form})

home/views.py
from django.shortcuts import render

def home_page(request):
    name = 'Hossain'
    title = 'Home'
    # u_name = request.POST
    context ={
        'name': name,
        'title':title,
    }
    return render(request, 'home/home.html', context)

products/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block title %} {% endblock %}

    <link rel="stylesheet" type="text/css" href="styel.css"/>

    <style>
        
        *{
            margin: 0;
        }

        a{
            text-decoration: none;
            color: cornsilk;
        }
        .nav{
            background-color: chocolate;
        }
        .nav .nav_box{
            width: 85%;
            margin: 0 auto;
            display: flex;            
            justify-content: space-between;
            padding: 30px 0;
            color: cornsilk;
        }
    </style>
</head>
<body>
    <!-- navbar -->

    <section>
        <div class="nav">
            <div class="nav_box">
                <div class="right">
                    <div class="log">
                        <a href="/">Logo</a>
                    </div>
                </div>
                <div class="left">
                    {% if user.is_authenticated %}
                    <a href="{% url 'accountApp:logoutUser' %}">Logout</a>
                    {% endif %}
                    <a href="{% url 'accountApp:registration' %}">Registration</a>
                </div>
            </div>
        </div>
    </section>

    {% block content %} {% endblock %}
</body>
</html>

templates/home/home.html
<!DOCTYPE html>
{% include 'base.html' %}

{% block title %}
    <title> {{ title }} </title>
{% endblock %}

{% block content %}
        Its home na.!
{% endblock %}